title: VanillaEvents Documentation
description: Ijeh
theme: just-the-docs

url: https://n33d4n4m3.github.io/VEDocs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
